import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "architecture",
    "self-host",
    {
      type: "category",
      label: "Guides",
      items: ["guides/api-client"],
    },
    {
      type: "category",
      label: "Library Reference",
      link: {
        type: "doc",
        id: "api/README",
      },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    "http/index",
  ],
};

export default sidebars;
