import type { Language } from "@/lib/i18n";

const copies = {
  vi: {
    followers: "Người theo dõi",
    following: "Đang theo dõi",
    follow: "Theo dõi",
    requested: "Đã gửi yêu cầu",
    unfollow: "Bỏ theo dõi",
    privateProfile: "Đây là tài khoản riêng tư",
    privateProfileHelp: "Theo dõi tài khoản này để xem heatmap và các buổi tập.",
    notifications: "Thông báo",
    noNotifications: "Chưa có thông báo.",
    viewAll: "Xem tất cả",
    markAllRead: "Đánh dấu tất cả đã đọc",
    accept: "Chấp nhận",
    decline: "Từ chối",
    followRequest: "đã gửi yêu cầu theo dõi bạn.",
    newFollower: "đã bắt đầu theo dõi bạn.",
    followAccepted: "đã chấp nhận yêu cầu theo dõi của bạn.",
    feed: "Bảng tin",
    feedDescription: "Những buổi tập công khai mới nhất từ người bạn theo dõi.",
    emptyFeed: "Chưa có buổi tập nào trong bảng tin.",
    loadMore: "Tải thêm",
    publicProfile: "Hồ sơ công khai",
    privateProfileSetting: "Hồ sơ riêng tư",
    privacyHelp: "Tài khoản riêng tư cần duyệt người theo dõi trước khi họ xem buổi tập.",
    privacyPublicWarning: "Chuyển sang công khai sẽ tự động chấp nhận các yêu cầu đang chờ.",
    privacySaved: "Đã cập nhật quyền riêng tư.",
    privacyFailed: "Chưa thể cập nhật quyền riêng tư.",
    connectionsPrivate: "Danh sách này chỉ dành cho người theo dõi đã được chấp nhận.",
  },
  en: {
    followers: "Followers",
    following: "Following",
    follow: "Follow",
    requested: "Requested",
    unfollow: "Unfollow",
    privateProfile: "This account is private",
    privateProfileHelp: "Follow this account to see its heatmap and workouts.",
    notifications: "Notifications",
    noNotifications: "No notifications yet.",
    viewAll: "View all",
    markAllRead: "Mark all as read",
    accept: "Accept",
    decline: "Decline",
    followRequest: "requested to follow you.",
    newFollower: "started following you.",
    followAccepted: "accepted your follow request.",
    feed: "Feed",
    feedDescription: "The latest public workouts from people you follow.",
    emptyFeed: "There are no workouts in your feed yet.",
    loadMore: "Load more",
    publicProfile: "Public profile",
    privateProfileSetting: "Private profile",
    privacyHelp: "Private accounts approve followers before they can see workouts.",
    privacyPublicWarning: "Going public automatically accepts pending requests.",
    privacySaved: "Privacy updated.",
    privacyFailed: "Unable to update privacy.",
    connectionsPrivate: "This list is only available to accepted followers.",
  },
} as const;

export function getSocialCopy(language: Language) {
  return copies[language];
}
