import type { Language } from "./i18n";

const copies = {
  vi: {
    followers: "Người theo dõi",
    following: "Đang theo dõi",
    follow: "Theo dõi",
    requested: "Đã gửi yêu cầu",
    unfollow: "Bỏ theo dõi",
    privateProfile: "Đây là tài khoản riêng tư",
    privateProfileHelp: "Theo dõi tài khoản này để xem heatmap và các buổi tập.",
    notifications: "Thông báo",
    noNotifications: "Chưa có thông báo.",
    someone: "Ai đó",
    viewAll: "Xem tất cả",
    markAllRead: "Đánh dấu tất cả đã đọc",
    accept: "Chấp nhận",
    decline: "Từ chối",
    followRequest: "đã gửi yêu cầu theo dõi bạn.",
    newFollower: "đã bắt đầu theo dõi bạn.",
    followAccepted: "đã chấp nhận yêu cầu theo dõi của bạn.",
    workoutLiked: "đã thích buổi tập của bạn.",
    workoutCommented: "đã bình luận về buổi tập của bạn.",
    feed: "Bảng tin",
    feedDescription: "Buổi tập công khai mới nhất của bạn và những người bạn theo dõi.",
    emptyFeed: "Chưa có buổi tập nào trong bảng tin.",
    searchError: "Chưa thể tìm người dùng.",
    searchLoading: "Đang tìm...",
    searchNoResults: "Không tìm thấy người dùng.",
    searchPlaceholder: "Tìm người dùng",
    loadMore: "Tải thêm",
    like: "Thích",
    unlike: "Bỏ thích",
    comments: "Bình luận",
    commentPlaceholder: "Viết bình luận...",
    postComment: "Đăng",
    editComment: "Sửa",
    deleteComment: "Xóa",
    saveComment: "Lưu",
    cancel: "Hủy",
    edited: "đã chỉnh sửa",
    viewWorkout: "Xem buổi tập",
    viewAllComments: (count: number) => `Xem tất cả ${count} bình luận`,
    loadEarlierComments: "Tải bình luận trước",
    signInToInteract: "Đăng nhập để thích hoặc bình luận.",
    signIn: "Đăng nhập",
    interactionFailed: "Chưa thể cập nhật. Vui lòng thử lại.",
    commentTooLong: "Bình luận tối đa 500 ký tự.",
    imageViewer: "Trình xem ảnh buổi tập",
    closeImageViewer: "Đóng trình xem ảnh",
    previousImage: "Ảnh trước",
    nextImage: "Ảnh tiếp theo",
    workoutImages: (count: number) => `${count} ảnh của buổi tập`,
    openImage: (index: number, count: number) => `Mở ảnh ${index} trên ${count}`,
    publicProfile: "Hồ sơ công khai",
    privateProfileSetting: "Hồ sơ riêng tư",
    privacyHelp: "Tài khoản riêng tư cần duyệt người theo dõi trước khi họ xem buổi tập.",
    privacyPublicWarning: "Chuyển sang công khai sẽ tự động chấp nhận các yêu cầu đang chờ.",
    privacySaved: "Đã cập nhật quyền riêng tư.",
    privacyFailed: "Chưa thể cập nhật quyền riêng tư.",
    connectionsPrivate: "Danh sách này chỉ dành cho người theo dõi đã được chấp nhận.",
  },
  en: {
    followers: "Followers",
    following: "Following",
    follow: "Follow",
    requested: "Requested",
    unfollow: "Unfollow",
    privateProfile: "This account is private",
    privateProfileHelp: "Follow this account to see its heatmap and workouts.",
    notifications: "Notifications",
    noNotifications: "No notifications yet.",
    someone: "Someone",
    viewAll: "View all",
    markAllRead: "Mark all as read",
    accept: "Accept",
    decline: "Decline",
    followRequest: "requested to follow you.",
    newFollower: "started following you.",
    followAccepted: "accepted your follow request.",
    workoutLiked: "liked your workout.",
    workoutCommented: "commented on your workout.",
    feed: "Feed",
    feedDescription: "The latest public workouts from you and people you follow.",
    emptyFeed: "There are no workouts in your feed yet.",
    searchError: "Unable to search users.",
    searchLoading: "Searching...",
    searchNoResults: "No users found.",
    searchPlaceholder: "Search users",
    loadMore: "Load more",
    like: "Like",
    unlike: "Unlike",
    comments: "Comments",
    commentPlaceholder: "Write a comment...",
    postComment: "Post",
    editComment: "Edit",
    deleteComment: "Delete",
    saveComment: "Save",
    cancel: "Cancel",
    edited: "edited",
    viewWorkout: "View workout",
    viewAllComments: (count: number) => `View all ${count} comments`,
    loadEarlierComments: "Load earlier comments",
    signInToInteract: "Sign in to like or comment.",
    signIn: "Sign in",
    interactionFailed: "Unable to update. Please try again.",
    commentTooLong: "Comments can contain up to 500 characters.",
    imageViewer: "Workout image viewer",
    closeImageViewer: "Close image viewer",
    previousImage: "Previous image",
    nextImage: "Next image",
    workoutImages: (count: number) => `${count} workout images`,
    openImage: (index: number, count: number) => `Open image ${index} of ${count}`,
    publicProfile: "Public profile",
    privateProfileSetting: "Private profile",
    privacyHelp: "Private accounts approve followers before they can see workouts.",
    privacyPublicWarning: "Going public automatically accepts pending requests.",
    privacySaved: "Privacy updated.",
    privacyFailed: "Unable to update privacy.",
    connectionsPrivate: "This list is only available to accepted followers.",
  },
} as const;

export function getSocialCopy(language: Language) {
  return copies[language];
}
