#!/usr/bin/env npx tsx
import { execSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import chalk from "chalk";
import { Command } from "commander";
import inquirer from "inquirer";
import ora from "ora";

const ROOT = resolve(import.meta.dirname, "..");
const ENV_PATH = resolve(ROOT, ".env");

type StorageProvider = "minio" | "cloudinary";

interface SetupAnswers {
  storageProvider: StorageProvider;
  clerkPublishableKey: string;
  clerkSecretKey: string;
  cloudinaryCloudName?: string;
  cloudinaryApiKey?: string;
  cloudinaryApiSecret?: string;
  startNow?: boolean;
}

function banner() {
  console.log();
  console.log(chalk.bold.cyan("  ┌─────────────────────────────┐"));
  console.log(chalk.bold.cyan("  │  Hope — Self-hosted setup   │"));
  console.log(chalk.bold.cyan("  └─────────────────────────────┘"));
  console.log();
}

function envExists(): boolean {
  return existsSync(ENV_PATH);
}

function loadEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {};
  const env: Record<string, string> = {};
  for (const line of readFileSync(ENV_PATH, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
  }
  return env;
}

function writeEnv(vars: Record<string, string>) {
  const lines = [
    "# Generated by: pnpm setup",
    "# Re-run `pnpm setup` to reconfigure.",
    "",
    "# --- Clerk (required) ---",
    `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ?? ""}`,
    `CLERK_SECRET_KEY=${vars.CLERK_SECRET_KEY ?? ""}`,
    "# Optional: Clerk Billing webhooks (Dashboard → Webhooks signing secret)",
    `CLERK_WEBHOOK_SIGNING_SECRET=${vars.CLERK_WEBHOOK_SIGNING_SECRET ?? ""}`,
    "",
    "# --- Storage ---",
    `STORAGE_PROVIDER=${vars.STORAGE_PROVIDER ?? "minio"}`,
  ];

  if (vars.STORAGE_PROVIDER === "cloudinary") {
    lines.push(
      `CLOUDINARY_CLOUD_NAME=${vars.CLOUDINARY_CLOUD_NAME ?? ""}`,
      `CLOUDINARY_API_KEY=${vars.CLOUDINARY_API_KEY ?? ""}`,
      `CLOUDINARY_API_SECRET=${vars.CLOUDINARY_API_SECRET ?? ""}`,
    );
  } else {
    lines.push(
      "",
      "# MinIO is auto-configured by docker compose (profile: minio).",
      "# Images are served through the API proxy at /api/storage/*",
    );
  }

  lines.push("");
  writeFileSync(ENV_PATH, lines.join("\n"), "utf-8");
}

function composeProfiles(provider: string): string[] {
  return provider === "minio" ? ["--profile", "minio"] : [];
}

function runCompose(args: string[], envProvider: string) {
  const cmd = ["compose", ...composeProfiles(envProvider), ...args];
  console.log(chalk.dim(`  $ docker ${cmd.join(" ")}`));
  console.log();
  const result = spawnSync("docker", cmd, { cwd: ROOT, stdio: "inherit" });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

async function promptSetup(existing: Record<string, string>): Promise<SetupAnswers> {
  return inquirer.prompt<SetupAnswers>([
    {
      type: "list",
      name: "storageProvider",
      message: "Image storage provider",
      choices: [
        {
          name: `${chalk.green("MinIO")}  — self-hosted (no external account, recommended)`,
          value: "minio",
          short: "MinIO",
        },
        {
          name: `${chalk.yellow("Cloudinary")}  — managed CDN (requires API keys)`,
          value: "cloudinary",
          short: "Cloudinary",
        },
      ],
      default: (existing.STORAGE_PROVIDER as StorageProvider) || "minio",
    },
    {
      type: "input",
      name: "clerkPublishableKey",
      message: "Clerk Publishable Key",
      default: existing.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY || undefined,
      validate: (v: string) =>
        v.startsWith("pk_") ? true : chalk.red("Must start with pk_ (from dashboard.clerk.com)"),
    },
    {
      type: "password",
      name: "clerkSecretKey",
      message: "Clerk Secret Key",
      default: existing.CLERK_SECRET_KEY || undefined,
      mask: "*",
      validate: (v: string) =>
        v.startsWith("sk_") ? true : chalk.red("Must start with sk_ (from dashboard.clerk.com)"),
    },
    {
      type: "input",
      name: "cloudinaryCloudName",
      message: "Cloudinary Cloud Name",
      default: existing.CLOUDINARY_CLOUD_NAME || undefined,
      when: (a) => a.storageProvider === "cloudinary",
      validate: (v: string) => (v.trim().length > 0 ? true : chalk.red("Required")),
    },
    {
      type: "input",
      name: "cloudinaryApiKey",
      message: "Cloudinary API Key",
      default: existing.CLOUDINARY_API_KEY || undefined,
      when: (a) => a.storageProvider === "cloudinary",
      validate: (v: string) => (v.trim().length > 0 ? true : chalk.red("Required")),
    },
    {
      type: "password",
      name: "cloudinaryApiSecret",
      message: "Cloudinary API Secret",
      default: existing.CLOUDINARY_API_SECRET || undefined,
      mask: "*",
      when: (a) => a.storageProvider === "cloudinary",
      validate: (v: string) => (v.trim().length > 0 ? true : chalk.red("Required")),
    },
    {
      type: "confirm",
      name: "startNow",
      message: "Start Docker stack now?",
      default: true,
    },
  ]);
}

async function runSetup(opts: { yes?: boolean } = {}) {
  banner();

  if (envExists() && !opts.yes) {
    const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
      {
        type: "confirm",
        name: "overwrite",
        message: chalk.yellow(".env already exists. Reconfigure?"),
        default: false,
      },
    ]);
    if (!overwrite) {
      console.log(chalk.dim("  Keeping existing .env."));
      console.log();
      console.log(`  Start with:  ${chalk.green("pnpm up")}`);
      console.log(`  Stop with:   ${chalk.green("pnpm down")}`);
      console.log();
      return;
    }
  }

  const existing = loadEnv();
  const answers = await promptSetup(existing);

  const spinner = ora("Writing .env").start();
  const envVars: Record<string, string> = {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: answers.clerkPublishableKey.trim(),
    CLERK_SECRET_KEY: answers.clerkSecretKey.trim(),
    STORAGE_PROVIDER: answers.storageProvider,
  };

  if (answers.storageProvider === "cloudinary") {
    envVars.CLOUDINARY_CLOUD_NAME = answers.cloudinaryCloudName!.trim();
    envVars.CLOUDINARY_API_KEY = answers.cloudinaryApiKey!.trim();
    envVars.CLOUDINARY_API_SECRET = answers.cloudinaryApiSecret!.trim();
  }

  writeEnv(envVars);
  spinner.succeed(`Wrote ${chalk.cyan(".env")} (storage: ${chalk.bold(answers.storageProvider)})`);

  if (answers.storageProvider === "minio") {
    console.log();
    console.log(chalk.dim("  MinIO stays internal — uploads go through the API proxy (Option B)."));
    console.log(chalk.dim("  Traefik exposes a single entrypoint at http://localhost"));
  }

  if (answers.startNow) {
    console.log();
    const upSpinner = ora("Building & starting Docker stack").start();
    try {
      runCompose(["up", "-d", "--build"], answers.storageProvider);
      upSpinner.succeed("Stack is up");
      console.log();
      console.log(`  ${chalk.bold("Web")}  ${chalk.underline("http://localhost")}`);
      console.log(`  ${chalk.bold("API")}  ${chalk.underline("http://localhost/api/health")}`);
      console.log();
    } catch {
      upSpinner.fail("Failed to start Docker stack");
      process.exit(1);
    }
  } else {
    console.log();
    console.log(chalk.bold("  Next steps:"));
    console.log();
    console.log(`  ${chalk.cyan("1.")} ${chalk.green("pnpm up")}     # start stack`);
    console.log(`  ${chalk.cyan("2.")} Open ${chalk.underline("http://localhost")}`);
    console.log();
  }
}

async function ensureEnvThen<T>(fn: () => Promise<T> | T) {
  if (!envExists()) {
    console.log(chalk.yellow("  No .env found — running setup first.\n"));
    await runSetup();
    if (!envExists()) process.exit(1);
  }
  return fn();
}

async function runUp(opts: { detach: boolean; build: boolean }) {
  await ensureEnvThen(() => {
    const env = loadEnv();
    const provider = env.STORAGE_PROVIDER ?? "cloudinary";
    const args = ["up"];
    if (opts.detach) args.push("-d");
    if (opts.build) args.push("--build");
    runCompose(args, provider);

    if (opts.detach) {
      console.log();
      console.log(`  ${chalk.bold("Web")}  ${chalk.underline("http://localhost")}`);
      console.log(`  ${chalk.bold("API")}  ${chalk.underline("http://localhost/api/health")}`);
      console.log();
    }
  });
}

async function runDown() {
  const env = loadEnv();
  const provider = env.STORAGE_PROVIDER ?? "cloudinary";
  runCompose(["down"], provider);
}

async function runStatus() {
  banner();
  const env = loadEnv();

  console.log(
    `  ${chalk.bold("Config")}   ${envExists() ? chalk.green(".env present") : chalk.red(".env missing")}`,
  );
  console.log(`  ${chalk.bold("Storage")}  ${chalk.cyan(env.STORAGE_PROVIDER ?? "(unset)")}`);
  console.log(
    `  ${chalk.bold("Clerk")}    ${env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ? chalk.green("configured") : chalk.red("missing")}`,
  );
  console.log();

  const spinner = ora("Checking Docker services").start();
  try {
    const out = execSync("docker compose ps --format json", {
      cwd: ROOT,
      encoding: "utf-8",
    });
    spinner.stop();

    const lines = out
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => JSON.parse(line) as { Name: string; State: string; Status: string });

    if (lines.length === 0) {
      console.log(chalk.dim("  No services running. Start with: pnpm up"));
    } else {
      for (const svc of lines) {
        const color = svc.State === "running" ? chalk.green : chalk.yellow;
        console.log(`  ${color("●")} ${svc.Name.padEnd(24)} ${svc.Status}`);
      }
    }
  } catch {
    spinner.fail("Unable to query docker compose");
  }
  console.log();
}

const program = new Command()
  .name("hope")
  .description("Hope self-host CLI — configure storage, auth, and Docker stack")
  .version("0.1.0");

program
  .command("setup")
  .description("Interactive setup wizard (storage provider + Clerk keys → .env)")
  .option("-y, --yes", "Overwrite .env without confirming")
  .action((opts) => runSetup(opts));

program
  .command("up")
  .description("Start Docker Compose stack (runs setup first if .env is missing)")
  .option("-d, --detach", "Run detached", true)
  .option("--no-detach", "Attach to logs")
  .option("--build", "Rebuild images before starting", false)
  .action((opts) => runUp(opts));

program.command("down").description("Stop Docker Compose stack").action(runDown);

program.command("status").description("Show config + running Docker services").action(runStatus);

program.parse();
