#!/usr/bin/env bash
# Load monorepo env and run wrangler with a local Hyperdrive connection string.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
API_DIR="$(cd "$(dirname "$0")/.." && pwd)"

set -a
# shellcheck disable=SC1091
[ -f "$ROOT/.env" ] && . "$ROOT/.env"
# shellcheck disable=SC1091
[ -f "$ROOT/.env.local" ] && . "$ROOT/.env.local"
set +a

if [ -z "${CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE:-}" ]; then
  if [ -n "${DATABASE_URL:-}" ]; then
    export CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE="$DATABASE_URL"
  else
    echo "error: set DATABASE_URL (or CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE) for local wrangler/Hyperdrive" >&2
    exit 1
  fi
fi

# Wrangler local secrets come from apps/api/.dev.vars (not the process env).
DEV_VARS="$API_DIR/.dev.vars"
{
  echo "# Generated by scripts/dev.sh — do not commit"
  for key in \
    CLERK_SECRET_KEY \
    CLERK_PUBLISHABLE_KEY \
    CLERK_WEBHOOK_SIGNING_SECRET \
    DATABASE_URL \
    CLOUDINARY_CLOUD_NAME \
    CLOUDINARY_API_KEY \
    CLOUDINARY_API_SECRET \
    STORAGE_PROVIDER \
    ALLOWED_ORIGINS
  do
    value="${!key:-}"
    if [ -n "$value" ]; then
      # Escape newlines; values are single-line secrets in this project.
      printf '%s=%s\n' "$key" "$value"
    fi
  done
} >"$DEV_VARS"

cd "$API_DIR"
exec pnpm exec wrangler dev "$@"
